[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"
  exclude = [
    './dist/app.html',
    './dist/cookie-policy.html',
    './dist/contattami.html', 
    './dist/comunita.html'
  ]

[[redirects]]
  from = '/api/*'
  to = 'https://json-corsi-fastify.herokuapp.com/:splat'
  status = 200
  force = true
  headers = {X-From = "Netlify"}