[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"
  exclude = [
    './dist/app.html',
    './dist/cookie-policy.html',
    './dist/contattami.html', 
    './dist/comunita.html'
  ]