module.exports = {
  pluginOptions: {
    prerenderSpa: {
      registry: undefined,
      renderRoutes: [
        '/',
        '/contattami',
        '/cookie-policy',
        '/tabella',
        '/tutti-i-corsi-di-laurea',
        '/corsi-di-laurea-unibo',
        '/corsi-di-laurea-unipi',
        '/corsi-di-laurea-bicocca',
        '/corsi-di-laurea-polimi',
        '/corsi-di-laurea-sapienza',
        '/corsi-di-laurea-uniba',
        '/corsi-di-laurea-unifi',
        '/corsi-di-laurea-unimi',
        '/corsi-di-laurea-unina',
        '/corsi-di-laurea-unipa',
        '/corsi-di-laurea-unipd',
        '/corsi-di-laurea-unipr',
        '/corsi-di-laurea-uniroma1',
        '/corsi-di-laurea-unisa',
        '/corsi-di-laurea-unito',
        '/lista-corsi-di-laurea-triennale',
        '/lista-corsi-di-laurea-triennale-ad-accesso-libero',
        '/lista-corsi-di-laurea-magistrale',
        '/lista-corsi-di-laurea-magistrale-a-ciclo-unico',
        '/corsi-di-laurea-triennale',
        '/corsi-di-laurea-triennali-ad-accesso-libero',
        '/corsi-di-laurea-magistrale-a-ciclo-unico',
        '/corsi-di-laurea-magistrale',
        '/universita',
        '/area-accademica',
        '/corsi-di-laurea-scienze-motorie',
        '/corsi-di-laurea-logopedia',
        '/corsi-di-laurea-lettere',
        '/corsi-di-laurea-informatica',
        '/corsi-di-laurea-giurisprudenza',
        '/corsi-di-laurea-farmacia',
        '/corsi-di-laurea-dietistica',
        '/corsi-di-laurea-biotecnologia',
        '/corsi-di-laurea-fisica',
        '/corsi-di-laurea-filosofia',
        '/corsi-di-laurea-biologia',
        '/corsi-di-laurea-scienze-della-formazione-primaria',
        '/corsi-di-laurea-matematica',
        '/corsi-di-laurea-infermieristica',
        '/corsi-di-laurea-storia',
        '/corsi-di-laurea-fisioterapia',
        '/corsi-di-laurea-psicologia',
        '/corsi-di-laurea-medicina',
        '/corsi-di-laurea-in-inglese',
        '/guida',
        '/citta',
        '/corsi-di-laurea-bari',
        '/corsi-di-laurea-bologna',
        '/corsi-di-laurea-firenze',
        '/corsi-di-laurea-genova',
        '/corsi-di-laurea-milano',
        '/corsi-di-laurea-napoli',
        '/corsi-di-laurea-padova',
        '/corsi-di-laurea-pavia',
        '/corsi-di-laurea-pisa',
        '/corsi-di-laurea-roma',
        '/corsi-di-laurea-torino',
        '/corsi-di-laurea-venezia',
        '/corsi-di-laurea-verona'
      ],
      useRenderEvent: true,
      headless: true,
      onlyProduction: true,
    }
  }
}

